services:
  postgres:
    image: postgres
    container_name: ${DB_NAME}
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASWD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pg_admin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  redis:
    image: redis:7.2
    container_name: ${REDIS_USER}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: unless-stopped

volumes:
  pg_data:
  pg_admin_data:
  redis_data: